baseURL = "https://llsd.de/"
languageCode = "de-DE"
title = "learn it | love it | save it"
disableHugoGeneratorInject = true

[params]
  email = "yann.duval@posteo.de"
  facebook = "https://facebook.com/yann.duval.16"
  padi = "395289"
  phone = "+49 176 856 22 373"