version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0
  hugo: circleci/hugo@1.0.0

jobs:
  deploy:
    executor: aws-cli/default

    steps:
      - aws-cli/setup
      - attach_workspace
      - run: aws s3 sync --delete ./public s3://$S3_TARGET/

workflows:
  version: 2
  build:
    jobs:
      - hugo/build:
          # Explicitly setting to default value to not be affected by
          # possible changes
          html-proofer: true
          hugo-env: production
          persist-to-workspace: true
          source: .
          destination: public

          # Default is latest
          # Using a specific version that is used during development.
          version: '0.76.3'

      - deploy:
          requires:
            - hugo/build
          filters:
            branches:
              only: main
